-- UZZAP2028 seed data.
--
-- Keep this file intentionally empty of template/sample application data.
-- Production-like test fixtures must be added through explicit test fixtures
-- or migrations that match the current UZZAP2028 schema.
