import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query"; import {getContent,listPollOptions,listContentFeed,createContent,toggleReaction,toggleSave,votePoll,getPollResults,listContentComments,addContentComment,repostContent} from "./api";
export function useContentFeed(roomId?:string|null,authorId?:string|null){return useQuery({queryKey:["content-feed",roomId??null,authorId??null],queryFn:()=>listContentFeed(roomId??null,authorId??null),staleTime:15_000,refetchOnReconnect:true});}
export function useContent(id:string){return useQuery({queryKey:["content",id],queryFn:()=>getContent(id),enabled:!!id,staleTime:30_000,refetchOnReconnect:true});}
export function usePollOptions(id:string,enabled=true){return useQuery({queryKey:["content-poll",id],queryFn:()=>listPollOptions(id),enabled:!!id&&enabled,staleTime:60_000,refetchOnReconnect:true});}
export function useCreateContent(){const qc=useQueryClient();return useMutation({mutationFn:(v:{roomId:string|null;kind:string;title:string|null;body:string|null;metadata?:Record<string,unknown>})=>createContent(v.roomId,v.kind,v.title,v.body,v.metadata??{}),onSuccess:()=>void qc.invalidateQueries({queryKey:["content-feed"]})});}
export function useToggleContentReaction(){const qc=useQueryClient();return useMutation({mutationFn:({contentId,reaction}:{contentId:string;reaction:string})=>toggleReaction(contentId,reaction),onSuccess:()=>void qc.invalidateQueries({queryKey:["content-feed"]})});}
export function useToggleContentSave(){const qc=useQueryClient();return useMutation({mutationFn:toggleSave,onSuccess:()=>void qc.invalidateQueries({queryKey:["content-feed"]})});}
export function usePollResults(id:string){return useQuery({queryKey:["content-poll-results",id],queryFn:()=>getPollResults(id),enabled:!!id,staleTime:5_000,refetchOnReconnect:true});}
export function useVotePoll(){const qc=useQueryClient();return useMutation({mutationFn:({contentId,optionId}:{contentId:string;optionId:string})=>votePoll(contentId,optionId),onSuccess:(_,v)=>{void qc.invalidateQueries({queryKey:["content-poll-results",v.contentId]});void qc.invalidateQueries({queryKey:["content-feed"]});}});}
export function useContentComments(id:string){return useQuery({queryKey:["content",id,"comments"],queryFn:()=>listContentComments(id),enabled:!!id,staleTime:15_000,refetchOnReconnect:true});}
export function useAddContentComment(){const qc=useQueryClient();return useMutation({mutationFn:({contentId,body,parentId}:{contentId:string;body:string;parentId?:string|null})=>addContentComment(contentId,body,parentId??null),onSuccess:(_,v)=>void qc.invalidateQueries({queryKey:["content",v.contentId,"comments"]})});}
export function useRepostContent(){const qc=useQueryClient();return useMutation({mutationFn:({contentId,roomId}:{contentId:string;roomId?:string|null})=>repostContent(contentId,roomId??null),onSuccess:()=>void qc.invalidateQueries({queryKey:["content-feed"]})});}