import {supabase} from "@/lib/supabase";
export type Room={id:string;name:string;description:string|null;province_code:string|null;kind:"public"|"private"|"group";is_locked?:boolean;view_only?:boolean;announcement?:string|null;members_can_invite?:boolean;pinned_message_id?:string|null};
export async function listRooms(limit=50,offset=0):Promise<Room[]>{const {data,error}=await supabase.rpc("list_public_rooms",{p_limit:limit,p_offset:offset});if(error)throw error;return (data??[]) as Room[];}
export async function joinRoom(roomId:string){const {data,error}=await supabase.rpc("join_room",{p_room_id:roomId});if(error)throw error;return data;}
export async function listOnlineRoomMembers(roomId:string,limit=50){const {data,error}=await supabase.rpc("list_online_room_members",{p_room_id:roomId,p_limit:limit,p_offset:0,p_online_for:"5 minutes"});if(error)throw error;return data??[];}
export async function listRoomCoHosts(roomId:string){const {data,error}=await supabase.rpc("list_room_co_hosts",{p_room_id:roomId});if(error)throw error;return data??[];}
export async function sendRoomMessage(roomId:string,body:string,kind="text",replyToId:string|null=null,metadata:Record<string,unknown>={}){const {data,error}=await supabase.rpc("send_room_message",{p_room_id:roomId,p_body:body,p_kind:kind,p_reply_to_id:replyToId,p_metadata:metadata});if(error)throw error;return data;}
export async function replyToRoomMessage(roomId:string,messageId:string,body:string,metadata:Record<string,unknown>={}){const {data,error}=await supabase.rpc("reply_to_room_message",{p_room_id:roomId,p_reply_to_message_id:messageId,p_body:body,p_metadata:metadata});if(error)throw error;return data;}
export async function sendRoomSticker(roomId:string,stickerId:string,metadata:Record<string,unknown>={}){const {data,error}=await supabase.rpc("send_room_sticker",{p_room_id:roomId,p_sticker_id:stickerId,p_media_id:null,p_metadata:metadata});if(error)throw error;return data;}
export async function toggleRoomMessageReaction(messageId:string,reaction:string){const {data,error}=await supabase.rpc("toggle_room_message_reaction",{p_message_id:messageId,p_reaction:reaction});if(error)throw error;return data;}
export async function markMessageRead(messageId:string){const {data,error}=await supabase.rpc("mark_message_read",{p_message_id:messageId});if(error)throw error;return data;}
export async function markRoomRead(roomId:string,readAt=new Date().toISOString()){const {data,error}=await supabase.rpc("mark_room_read",{p_room_id:roomId,p_read_at:readAt});if(error)throw error;return data;}
export async function setRoomMessageMentions(messageId:string,userIds:string[]){const {data,error}=await supabase.rpc("set_room_message_mentions",{p_message_id:messageId,p_mentioned_user_ids:userIds});if(error)throw error;return data;}
export async function listRoomMessages(roomId:string,beforeCreatedAt:string|null=null,beforeId:string|null=null,limit=50){const {data,error}=await supabase.rpc("list_room_messages",{p_room_id:roomId,p_before_created_at:beforeCreatedAt,p_before_id:beforeId,p_limit:limit});if(error)throw error;return Array.isArray(data)?data:(data?.items??[]);}

export async function setRoomPinnedMessage(roomId:string,messageId:string|null){const {data,error}=await supabase.rpc("set_room_pinned_message",{p_room_id:roomId,p_message_id:messageId});if(error)throw error;return data;}
export async function setRoomLock(roomId:string,locked:boolean,reason:string|null=null){const {data,error}=await supabase.rpc("set_room_lock",{p_room_id:roomId,p_locked:locked,p_reason:reason});if(error)throw error;return data;}
export async function setRoomChatSettings(roomId:string,announcement:string|null,viewOnly:boolean,membersCanInvite:boolean){const {data,error}=await supabase.rpc("set_room_chat_settings",{p_room_id:roomId,p_announcement:announcement,p_view_only:viewOnly,p_members_can_invite:membersCanInvite});if(error)throw error;return data;}
export async function moderateRoomMember(roomId:string,targetUserId:string,action:string,durationMinutes:number|null,reason:string){const {data,error}=await supabase.rpc("moderate_room_member",{p_room_id:roomId,p_target_user_id:targetUserId,p_action:action,p_duration_minutes:durationMinutes,p_reason:reason});if(error)throw error;return data;}
export async function kickRoomMember(roomId:string,targetUserId:string,allowRejoin:boolean,reason:string){const {data,error}=await supabase.rpc("kick_room_member",{p_room_id:roomId,p_target_user_id:targetUserId,p_allow_rejoin:allowRejoin,p_reason:reason});if(error)throw error;return data;}
export async function moderateRoomMessage(messageId:string,action:string,reason:string){const {data,error}=await supabase.rpc("moderate_room_message",{p_message_id:messageId,p_action:action,p_reason:reason});if(error)throw error;return data;}
export async function strikeRoomMember(roomId:string,targetUserId:string,durationMinutes:number,reason:string){const {data,error}=await supabase.rpc("strike_room_member",{p_room_id:roomId,p_target_user_id:targetUserId,p_duration_minutes:durationMinutes,p_reason:reason});if(error)throw error;return data;}
export async function listRoomReports(roomId:string,status:string="open",limit=30,offset=0){const {data,error}=await supabase.rpc("list_room_reports",{p_room_id:roomId,p_status:status,p_limit:limit,p_offset:offset});if(error)throw error;return data??[];}
export async function createRoomReport(roomId:string,messageId:string|null,reportedUserId:string|null,reason:string){const {data,error}=await supabase.from("reports").insert({room_id:roomId,message_id:messageId,reported_user_id:reportedUserId,reason}).select().single();if(error)throw error;return data;}

export async function getMyRoomMembership(roomId:string){const {data,error}=await supabase.from("room_members").select("room_id,user_id,role,nickname,chat_notifications_enabled,is_pinned").eq("room_id",roomId).maybeSingle();if(error)throw error;return data;}

export async function listRoomMembers(roomId:string,limit=100,offset=0){const {data,error}=await supabase.rpc("list_room_members",{p_room_id:roomId,p_limit:limit,p_offset:offset});if(error)throw error;return data??[];}
export async function listRoomCoHostRequests(roomId:string,status?:string){let query=supabase.from("room_co_host_requests").select("id,room_id,requester_id,target_user_id,status,created_at,responded_at").eq("room_id",roomId).order("created_at",{ascending:false});if(status)query=query.eq("status",status);const {data,error}=await query;if(error)throw error;return data??[];}
export async function setRoomCoHost(roomId:string,targetUserId:string,enabled:boolean){const {data,error}=await supabase.rpc("set_room_co_host",{p_room_id:roomId,p_target_user_id:targetUserId,p_enabled:enabled});if(error)throw error;return data;}
export async function requestRoomCoHost(roomId:string,targetUserId:string){const {data,error}=await supabase.rpc("request_room_co_host",{p_room_id:roomId,p_target_user_id:targetUserId});if(error)throw error;return data;}
export async function acceptRoomCoHostRequest(requestId:string){const {data,error}=await supabase.rpc("accept_room_co_host_request",{p_request_id:requestId});if(error)throw error;return data;}
export async function declineRoomCoHostRequest(requestId:string){const {data,error}=await supabase.rpc("decline_room_co_host_request",{p_request_id:requestId});if(error)throw error;return data;}
export async function cancelRoomCoHostRequest(requestId:string){const {data,error}=await supabase.rpc("cancel_room_co_host_request",{p_request_id:requestId});if(error)throw error;return data;}

export async function updateRoomReport(reportId:string,status:"reviewing"|"resolved"|"dismissed",resolution:string|null){const {data,error}=await supabase.from("reports").update({status,resolution,resolved_by:status==="resolved"||status==="dismissed"?(await supabase.auth.getUser()).data.user?.id:null,resolved_at:status==="resolved"||status==="dismissed"?new Date().toISOString():null}).eq("id",reportId).select().single();if(error)throw error;return data;}

export async function listRoomModerationHistory(roomId:string,limit=50){const {data,error}=await supabase.from("moderation_actions").select("id,room_id,moderator_id,target_user_id,target_message_id,action,reason,metadata,created_at").eq("room_id",roomId).order("created_at",{ascending:false}).limit(limit);if(error)throw error;return data??[];}
